### ISSUE TITLE
point.sensitivity causes issue when set to "radius" or function

### ISSUE THREAD

**Issue by kisyov21** [naver/billboard.js#3900]
## Description

I am describing two issues that I found with point.sensitivity. Both are affecting our users on production, especially the second one is blocking the users from using the whole feature that relies on it.
I am using **3.13.0**@billboard.js 
1. If point.sensitivity is 'radius', click on the empty area of the chart leads to an error : 
![image](https://github.com/user-attachments/assets/e4331efc-a1e2-4457-9b9d-668e8c563ed2)

 **billboard.js:14346 Uncaught TypeError: Cannot read properties of undefined (reading 'r')
    at SVGRectElement.clickHandlerForMultipleXS (billboard.js:14346:73)
    at SVGRectElement.<anonymous> (billboard.js:14322:46)
    at SVGRectElement.<anonymous> (d3.v7.min.js:2:20686)**

2. If point.sensitivity is a function then data.onclick is not working fired. 
![image](https://github.com/user-attachments/assets/4f9000ee-7e70-4a3b-8836-cfef7c74cfb0)

## Steps to check or reproduce
Here I am attaching simple code that I took from your demo examples, I only extended point.sensitivity=Function example with data.onclick to illustrate the problem.
[example.txt](https://github.com/user-attachments/files/17364092/example.txt)

**Comment by netil** [comment]
Hi @kisyov21, confirmed the issue. Thanks for the report.

**Comment by netil** [comment]
released the RC version with the fix.
try by installing,

```sh
$ npm i billboard.js@next
```

**Comment by kisyov21** [comment]
@netil I confirm that the first issue is resolved, but the second one still persists.
**2.If point.sensitivity is a function then data.onclick is not working.**
